### ISSUE TITLE
In relation_member mapping is applied to member, not relation

### ISSUE THREAD

**Issue by andreynovikov** [omniscale/imposm3#129]
[Documentation](https://imposm.org/docs/imposm3/latest/relations.html#example) says that mapping is done on relation tags, but when I try to use `type: [building]` mapping it produces empty table. But when I change it to `building: [__any__]` mapping it produces table that contains all the buildings found in relations. But this is not what I want as it also contains all multipolygons.

**Comment by andreynovikov** [comment]
No, I'm wrong. But I still fail to import building relation members. Investigating it further...

**Comment by andreynovikov** [comment]
Ok, the title is incorrect but the bug exists. Trying to import the mapping:

```
tables:
  building_parts:   
    type: relation_member
    columns:         
      - name: osm_id 
        type: id
      - name: member
        type: member_id
      - name: role   
        type: member_role
      - name: type   
        key: type
        type: string
    mapping:         
      type: [building]
```

produces empty table unless I add:

````
tags:
  load_all: true
```
