### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by andreynovikov** [omniscale/imposm3#130]
I have the following mapping:

```
tables:
  buildings:
    type: polygon
    fields:
    - name: osm_id
      type: id
    - name: geometry
      type: geometry
    - name: building
      type: mapping_value
    - name: name
      key: name
      type: string
    mapping:
      building: [__any__]
```

If applied to the [following building](http://www.openstreetmap.org/relation/4281592) resulting table contains entry for relation with values only from relation keys but it does not contain the [corresponding way](http://www.openstreetmap.org/way/166560022). As you see the problem is that most of the data is applied to the way but it's lost.
