### ISSUE TITLE
Incorrect documentation of bool type

### ISSUE THREAD

**Issue by jirik** [omniscale/imposm3#157]
[Imposm3 doc](https://imposm.org/docs/imposm3/latest/mapping.html#bool) says:
> `bool`
> Convert true, yes and 1 values to true, otherwise use false.

However [source code is doing something else](https://github.com/omniscale/imposm3/blob/20ad581d9bc3e17a198d881f571b644eff0235f3/mapping/columns.go#L64:L69):
```go
func Bool(val string, elem *element.OSMElem, geom *geom.Geometry, match Match) interface{} {
	if val == "" || val == "0" || val == "false" || val == "no" {
		return false
	}
	return true
}
```

From the documentation, I thought that using this setup
```yaml
...
    fields:
    - key: tunnel
      name: is_tunnel
      type: bool
```
imposm3 will convert `tunnel=culvert` to `false`, but it was converted to `true`.
