### ISSUE TITLE
Missing administrative boundary relations

### ISSUE THREAD

**Issue by HansonYip** [omniscale/imposm3#195]
Hi, guys

I am importing [china.osm.pbf](http://download.geofabrik.de/asia/china-latest.osm.pbf) into PostGIS with the mapping file as below:
```yaml
generalized_tables: {}
tables:
  border_relations:
    type: relation
    relation_types: [boundary]
    mapping:
      boundary: [administrative]
    columns:
      - {name: osm_id, type: id}
      - {name: admin_level, key: admin_level, type: integer}
      - {name: name, key: name, type: string}
```
But I found that all of those boundary relations with `admin_level=2` are lost. Actually, I am sure that the china.osm.pbf file contains at least one.

Is it the same problem as #126 ?
