### ISSUE TITLE
Optimize housenumbers table

### ISSUE THREAD

**Issue by Sylade** [omniscale/imposm3#204]
Hello
With your example-mapping.yml, I remark in the table housenumbers generated by your imposm that:
- there are several empty names (3th field). 
- there are several identical names with the very near goemetries (< 1 meter)

Is it possible to remove them during imposm to optimize the table?
Thank you.

**Comment by olt** [comment]
This is just an example mapping. This file is not maintained to provide an optimized, modern OSM map.

**Comment by Sylade** [comment]
Hi olt,
Maybe, it wasn't clear enough.
I use your example mapping and I don't how to add a criteria to avoid the empty name in the housenumbers table.
I tried with reject filters but it isn't working:
```
tables:
  amenities:
    columns:
    - name: osm_id
      type: id
    - name: geometry
      type: geometry
    - key: name
      name: name
      type: string
    - name: type
      type: mapping_value
    filters:
      reject:
        name: [""]
    mapping:
      amenity:
      - bar
```
It is possible to add a criteria in the mapping to avoid the empty names?

I see in your your exemple mapping:
```
  landusages_gen0:
    source: landusages_gen1
    sql_filter: ST_Area(geometry)>500000.000000
    tolerance: 200.0
```
It is possible to use a similar criterion in mapping to remove the identical names with the very near goemetries (< 1 meter)?

Thank you for to reopen this issue.
