### ISSUE TITLE
Add support for tag values for areas

### ISSUE THREAD

**Issue by zdila** [omniscale/imposm3#253]
## Context

Currently `areas.area_tags` and `areas.linear_tags` contain only keys, not complete tags (_`key=value`_). I think adding support also for value would be very useful. Please consider for example key `natural` which is for some values area (`water`, `scrub`) and for other values line (`cliff`, `valey`).

## Expected Behavior

Example definition could look like this. I only added support for `natural=cliff` to existing sample.

```yaml
  area_tags:
    - building
    - landuse
    - leisure
    - natural
    - aeroway
  linear_tags:
    - highway
    - barrier
    - key: natural
      value: cliff
```

## Actual Behavior

Currently circular way tagged with `natural=cliff` is not imported for tables with `type: linestring`.
