### ISSUE TITLE
hstore_tags include by mask

### ISSUE THREAD

**Issue by alx77** [omniscale/imposm3#281]
Hello, is there any way to pick up only name tags, like this
```
    - type: hstore_tags
      name: names
      include: ["name:*"]
      key:
```
I tried with/without `load_all` - doesn't work. Excluding is very cumbersome because there are various tags inside.
