### ISSUE TITLE
Generalized relation_member tables are loosing records during update

### ISSUE THREAD

**Issue by zdila** [omniscale/imposm3#293]
```
generalized_tables:
  route_members_gen1:
    source: route_members
    tolerance: 50
tables:
  type: relation_member
    relation_types:
      - route
    mapping:
      route:
        - hiking
    columns:
      - name: osm_id
        type: id
      - name: member
        type: member_id
      - name: geometry
        type: geometry
      - name: role
        type: member_role
        key: role
      - name: type
        type: member_type
```

On initial import the table `route_members_gen1` is correctly populated but during longer period of applying minutely updates the records from `route_members_gen1` starts to disappear - all members of a (modified?) route at once.
