### ISSUE TITLE
Missing and empty polygons after import (related to building and parts)

### ISSUE THREAD

**Issue by Joxit** [omniscale/imposm3#295]
## Context

I'm trying to import buildings/polygons from OSM, some of them are defining multi part buildings (with parts of different heights/levels).

I tried to import the data using `polygon` and `geometry` mappings, they both fail with different behaviors:
- The geometry mapping will import the data with a `POLYGON EMPTY` geometry
- The polygon mapping will ignore the data 

My example is [relation/13155725](https://www.openstreetmap.org/relation/13155725), you can get download the gzipped data from direct dowload [relation-13155725.osm.pbf.gz](https://github.com/omniscale/imposm3/files/15235882/relation-13155725.osm.pbf.gz) and [relation-13155725.osm.xml.gz](https://github.com/omniscale/imposm3/files/15235883/relation-13155725.osm.xml.gz)  or get the XML from [overpass](https://overpass-turbo.eu/) using this query:
```
[out:xml][timeout:25];
rel(13155725)({{bbox}});
(._;>;);
out;
```

I did some experiments (removing some parts) and it seems that the member of a relation `type=building` with the  `role=part` is considered as a inner hole of a multi polygon. Since in this example the union of all parts equals the outline, the polygon disappear, that's why the result is  `POLYGON EMPTY`.

I need both of the geometries for their tags and sometime relations have more information than outlines. 

## Expected Behavior

When getting data for both tables `osm_test_buildings_geom` and `osm_test_buildings_poly`, the geometry should be (at least)  the outline polygon.

```
postgres=# select osm_id, ST_AsText(geometry)  from osm_test_buildings_geom where osm_id = -13155725;
  osm_id   |             st_astext
-----------+---------------------------------
 -13155725 | POLYGON((976945.8716064208....))
```

## Actual Behavior

```
postgres=# select osm_id, ST_AsText(geometry)  from osm_test_buildings_geom where osm_id = -13155725;
  osm_id   |   st_astext   
-----------+---------------
 -13155725 | POLYGON EMPTY
```

## Possible Fix

Filter `role=parts` members when creating buildings. This will result to have two polygons, the outline (if the tag `building=*` is present) and the relation.

A workaround for those passing by is using a relation mapping and doing an `SQL JOIN`.

## Steps to Reproduce

Mapping configuration:

```yaml
tags:
  load_all: true
tables:
  test_buildings_poly:
    fields:
    - name: osm_id
      type: id
    - name: geometry
      type: geometry
    - name: tags
      type: hstore_tags
    mapping:
      building:
      - __any__
    type: polygon
  test_buildings_geom:
    fields:
    - name: osm_id
      type: id
    - name: geometry
      type: geometry
    - name: tags
      type: hstore_tags
    type_mappings:
      polygons:
        building:
        - __any__
    type: geometry
```

1. Download [relation-13155725.osm.pbf.gz](https://github.com/omniscale/imposm3/files/15235882/relation-13155725.osm.pbf.gz)
2. import with the above configuration
3. The table `osm_test_buildings_geom` should have 2 geometries, [way/978521649](https://osm.org/way/978521649) with the correct geometry and [relation/13155725](https://osm.org/relation/13155725) with an empty polygon
4. The table `osm_test_buildings_poly` should have 1 geometry, [way/978521649](https://osm.org/way/978521649) with the correct geometry

## Your Environment

* Version used: Imposm3 v0.12.0
* Environment name and version: PostgreSQL 11 with PostGIS 3.3
* Server type and version: Docker 26.1.1
* Operating System and version: Postgres under Alpine Linux & Imposm3 under Debian Bookworm
