### ISSUE TITLE
[Feature request] categorize_bool

### ISSUE THREAD

**Issue by Jomy10** [omniscale/imposm3#299]
We currnetly have a categorize_int, but a categorize_bool would also be useful.

Example below would add a column which is `true` when a road is paved.

```yaml
- name: paved
  type: categorize_bool
  keys: [surface]
  args:
    default: false
    values:
      "paved": true
      "asphalt": true
      "chipseal": true
      "concrete": true
      "concrete:lanes": true
      "concrete:plates": true
      "paving_stones": true
      "paving_stones:lanes": true
      "grass_paver": true
      "sett": true
      "unhewn_cobblestone": true
      "cobblestone": true
      "cobblestone:flattened": true
      "bricks": true
      "metail": true
      "metal_grid": true
      "wood": true
      "stepping_stones": true
      "rubber": true
      "tiles": true
```
