### ISSUE TITLE
Relations not working?

### ISSUE THREAD

**Issue by JanJakes** [omniscale/imposm3#96]
Are the relations working? My mapping goes like:

```yaml
tables:
  destinations:
    type: relation
    fields: ...
    mapping: ...

  destination_members:
    type: relation_member
    fields: ...
    mapping: ...

tags:
  load_all: true
```

But I get the following error:

```
SQL Error: pq: Invalid type name "RELATION(2)" - valid ones are:
	POINT, MULTIPOINT,
	LINESTRING, MULTILINESTRING,
	POLYGON, MULTIPOLYGON,
	CIRCULARSTRING, COMPOUNDCURVE, MULTICURVE,
	CURVEPOLYGON, MULTISURFACE,
	GEOMETRY, GEOMETRYCOLLECTION,
	POINTM, MULTIPOINTM,
	LINESTRINGM, MULTILINESTRINGM,
	POLYGONM, MULTIPOLYGONM,
	CIRCULARSTRINGM, COMPOUNDCURVEM, MULTICURVEM
	CURVEPOLYGONM, MULTISURFACEM, TRIANGLE, TRIANGLEM,
	POLYHEDRALSURFACE, POLYHEDRALSURFACEM, TIN, TINM
	or GEOMETRYCOLLECTIONM in query SELECT AddGeometryColumn('import', 'osm_destinations', 'geometry', '3857', 'RELATION', 2);
```

I've tried installation from source and latest version from http://imposm.org/static/rel/ (including relations-dev).
